spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              -http://localhost:3000
              -http://localhost:8087
              -http://localhost:8686
              -http://localhost:9090

            #            allowedHeaders:
            #              - content-type
            #              - authorization
            #              - access-control-origin
            allowedMethods:
              - GET
              - POST
              - OPTIONS