eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    healthcheck:
      enabled: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    root: info
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders:
              - content-type
            allowedMethods:
              - GET
              - POST
              - OPTIONS
  profiles:
  #active: dev
management:
  endpoint:
    health:
      show-details: always
server:
  port: 9090
global:
  trace:
    local: false
    statistics: true
    audit: true